### ISSUE TITLE
PUT endpoint without trailing slash does nothing

### ISSUE THREAD

**Issue by karlb** [Layr-Labs/eigenda-proxy#88]
The [OP alt-DA spec](https://specs.optimism.io/experimental/alt-da.html#da-server) requires
```
Request:
  POST /put
  Content-Type: application/octet-stream
  Body: <preimage_bytes>

Response:
  200 OK
  Content-Type: application/octet-stream
  Body: <hex_encoded_commitment>
```

The EigenDA proxy does not react on that URL and silently returns nothing, but it does work when appending a slash to the URL (which is not included in the spec).

```
karl@PVTY25Y2GX ~> curl -X POST http://127.0.0.1:3100/put --data foo -s | wc
       0       0       0
karl@PVTY25Y2GX ~> curl -X POST http://127.0.0.1:3100/put/ --data foo -s | wc
       0      13     187
```

Suggested changes:
* Respond with commitment at `/put`
* Respond with HTTP code 404 on unknown URLs

PS: The response does also not look hex-encoded, but that is a separate issue
